name: Publish

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools build-essential cmake git
        ./install_dependencies.sh
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        ./get_openvino_repo.sh
        ./build_doxygen.sh
        ./get_doxygen_rst.sh
        ./get_zoo_models.sh
        ./get_notebooks.sh
        sphinx-build -b html . _build/html
    - name: Deploy the docs
      run: |
        mv _build/html $HOME/output
        cd $HOME/output
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest html output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.ACCESS_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:latestHTML